### ISSUE TITLE
本地运行

### ISSUE THREAD

**Issue by Tanaoaaa** [cdfan/my-admin#1]
你好，在看了你的my-admin项目后，将项目下载到了本地，但本地不知道为什么无法运行，有空能否解答此问题，本人qq:758551436
![企业微信截图_16089663128756](https://user-images.githubusercontent.com/40811370/103147047-f1577900-478b-11eb-9a3f-c0e7ae58b3cf.png)

**Comment by cdfan** [comment]
现在是部分开源呢，所以本地无法运行不过部分功能的代码是完全可以查看的，如果有需要可以持续关注哈，后面会考虑完全开源
