### ISSUE TITLE
挺好的，但是没全开源可惜了

### ISSUE THREAD

**Issue by tlerbao** [cdfan/my-admin#2]
比如想看看DictSelect组件怎么写的，字典的组件是否还有其他，看看这块怎么设计的哈。

加油，感谢开源！

**Comment by cdfan** [comment]
DictSelect组件主要就是一个下拉组件而已，只不过可以通过业务字典模块维护的字典编码获取到字典详情信息。他接收一个字典编码然后组件中在通过传入的字典编码查询对应的字典详情然后显示在下拉框中。这样要在下拉框中要显示那些字典详情，只需要传入对应的字典编码就可以了

**Comment by tlerbao** [comment]
@cdfan 嗯，我在想字典的展现形式可能不光只有select下拉一种，还有可能是多选，radio等，是否再传个组件类型动态渲染相应的组件更好呢哈。

**Comment by cdfan** [comment]
下拉多选可以支持，至于其他的后面如果有这种需求可以弄一下哈。

**Comment by tlerbao** [comment]
@cdfan 从您这里学到封装DictSelect组件来快速调用字典数据并生成select 在表单里是挺方便了，请教一下，在表格数据中，要将数据的列回显成相应的字典label，这个您是怎么做的呢？
